config/routes.rb
Rails.application.routes.draw do

  post 'employee_token' => 'employee_token#create'
  devise_for :customers
  devise_for :employees

  namespace :admin do
    resources :restaurants, except: [:index, :create, :destroy]
    resources :locations, except: [:show] do
      resources :menus, only: [:index, :new]
    end
    resources :menus, except: [:new, :show] do
      resources :sections, only: [:new, :create]
    end
    resources :categories do
      resources :category_sections, only: [:new]
    end
    resources :category_sections, except: [:index, :show, :new] do
      resources :category_options, only: [:new]
    end
    resources :category_options, except: [:index, :show, :new]
    resources :items, except: [:show]
    resources :sections, only: [:edit, :update, :destroy] do
      resources :section_items, only: [:new, :create]
    end
    resources :section_items, only: [:edit, :update, :destroy]
    resources :employees
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:show]
    root to: "orders#index"
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post 'firebase_registrations' => "firebase_registrations#update"
      resources :orders, only: [:update]
      resources :locations do
        resources :orders, only: [:index]
      end
      resources :restaurants, only: [:index]
    end
  end

  resources :restaurants, only: [:show]

  get '/restaurants' => "restaurants#show", as: :customer_root
  resources :orders, only: [:new, :create]

  resources :menus, only: [:show]
  resources :locations, only: []  do
    resources :menus, only: [:index]
  end

  resources :items, only: [] do
    resources :bag_items, only: [:new]
  end
  resources :bag_items, only: [:create, :destroy]
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :restaurant
  has_many :orders
  has_many :menus, -> { order(:position) }, dependent: :destroy
  has_many :bags, dependent: :destroy

  acts_as_list

  before_save   :downcase_email

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z]+[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :location, presence: true, length: { maximum: 100 }
  validates :address, presence: true, length: { maximum: 100 }
  validates :city, presence: true, length: { maximum: 100 }
  validates :state, presence: true, length: { maximum: 2 }
  # TODO: Review zipcode when start including other countries
  validates :zipcode, presence: true, numericality: true,
  length: { minimum: 5, maximum: 5 }
  validates :country, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 100 },
  format: { with: VALID_EMAIL_REGEX }
  validates :position, numericality: { minimum: 1, only_integer: true }
  validates :tax, presence: true,
  numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }

  scope :sorted, -> { order(:position) }

  scope :from_restaurant, ->(restaurant_id) { where(restaurant_id: restaurant_id) }

  scope :with_visible_menus, -> { joins(:menus).where(menus: { visible: true }).distinct }

  def created
    to_milliseconds(self.created_at)
  end

  def updated
    to_milliseconds(self.updated_at)
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email.downcase!
    end
end

app/controllers/admin/locations_controller.rb
# Controller that handles location actions logic. It's a subclass of admin controller as it's an admin controller.
class Admin::LocationsController < Admin::AdminController
  before_action :authenticate_employee!, except: [:index]
  before_action :set_location, only: [:edit, :update, :destroy]

  layout 'admin'

  # GET /admin/locations
  # GET /admin/locations.js
  def index
    @locations = Location.sorted
    respond_to do |format|
      format.html {
        render '_index'
      }
      format.js
    end
  end

  # GET /admin/locations/new
  # GET /admin/locations/new.js
  def new
    @location = Location.new
    @locations_count = Location.count + 1
  end

  # POST /admin/locations
  # POST /admin/locations.js
  def create
    @location = Location.new(location_params)
    @location.restaurant_id = current_employee.restaurant_id
    respond_to do |format|
      if @location.save
        restaurant = @location.restaurant\
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.js {
          @locations = Location.sorted
          flash[:notice] = "Location was successfully created."
          render :index
        }
      else
        format.html {
          render :new
        }
        format.js {
          @locations_count = Location.count + 1
          render :new
        }
      end
    end
  end

  # GET /admin/locations/1/edit
  # GET /admin/locations/1/edit.js
  def edit
    @locations_count = Location.count
  end

  # PATCH/PUT /admin/locations/1
  # PATCH/PUT /admin/locations/1.js
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.js {
          @locations = Location.sorted
          flash[:notice] = "Location was successfully updated."
          render :index
        }
      else
        format.html { render :edit }
        format.js {
          @locations_count = Location.count
          render :edit
        }
      end
    end
  end

  # DELETE /admin/locations/1.js
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully deleted.' }
      format.js {
        @locations = Location.sorted
        flash[:notice] = "Location was successfully deleted."
        render :index
      }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:location, :address, :city, :state, :zipcode, :country, :email, :email_confirmation, :position, :tax, :time)
    end

end

app/helpers/api/v1/locations_helper.rb
module Api::V1::LocationsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
  COLORS = {0 => "success", 1 => "info", 2 => "warning", 3 => "danger"}
  def definePanel(count)
    COLORS[count % 4]
  end
end

app/views/admin/locations/_form.html.erb
<%= form_for(@location, url: url, remote: remote) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.select :state, options_for_select(ApplicationHelper::US_STATES, @location.state), {}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode, size: 5, minlength: 5, maxlength: 5, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :time %>
    <%= f.text_field :time, size: 5, min: 1, max: 2400, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :country %>
    <%= f.select :country, options_for_select(ApplicationHelper::COUNTRY_CODES.invert), {}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :position %>
    <%= f.select :position, 1..@locations_count, {}, { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.label :tax %>
    <div class="input-group">
      <%= f.text_field :tax, size: 5, minlength: 1, maxlength: 5, class: "form-control" %>
      <span class="input-group-addon">%</span>
    </div>
  </div>

  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/locations/_index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h1>
    Locations
    <!-- We use remote to use Ajax  -->
    <%= link_to new_admin_location_path, remote: true do %>
      <i class="fa fa-fw fa-plus-square" data-toggle="tooltip" data-placement="top" title="Add a location"></i>
    <% end %>
  </h1>
</div>

<!-- We include the modal form which will be loaded through boostrap javascript
     when clicking on the add or update icon -->
<%= render 'application/modal_form' %>

<div class="row">
  <% count = 0 %>
  <% @locations.each do |location| %>
    <div class="col-sm-6 col-lg-4 col-md-4">
        <div class="panel panel-<%= definePanel(count) %>">
            <div class="panel-heading">
                <h3 class="panel-title">
                  <%= location.location %>
                  <%= link_to admin_location_path(location.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
                    <i class="fa fa-fw fa-trash-o pull-right" data-toggle="tooltip" data-placement="top" title="Remove this location"></i>
                  <% end %>
                  <%= link_to edit_admin_location_path(location.id), remote: true do %>
                    <i class="fa fa-fw fa-pencil-square-o pull-right" data-toggle="tooltip" data-placement="top" title="Update this location"></i>
                  <% end %>
                </h3>
            </div>
            <div class="panel-body">
                <ul>
                  <li><%= location.address %></li>
                  <li><%= "#{location.city}, #{location.state}" %></li>
                  <li><%= location.zipcode %></li>
                  <li><%= ApplicationHelper::COUNTRY_CODES[location.country] %></li>
                  <li><%= location.email %></li>
                  <li>Tax Rate: <%= location.tax %> %</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- /.col-sm-4 -->
    <% count += 1 %>
  <% end %>
</div>

app/views/admin/locations/edit.js.erb
$('#modalFormBody').html("<%= escape_javascript(render 'form', url: admin_location_path(@location.id), remote: true) %>");
$('#modalForm').modal('show');
$('#modalFormTitle').html("Update Location");

app/views/admin/locations/index.js.erb
$('.main').html("<%= escape_javascript(render 'index') %>");
$('#modalForm').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
initTooltip();

app/views/admin/locations/new.js.erb
$('#modalFormBody').html("<%= escape_javascript(render 'form', url: admin_locations_path, remote: true) %>");
$('#modalForm').modal('show');
$('#modalFormTitle').html("Add a Location");