config/routes.rb
Rails.application.routes.draw do

  post 'employee_token' => 'employee_token#create'
  devise_for :customers
  devise_for :employees

  namespace :admin do
    resources :restaurants, except: [:index, :create, :destroy]
    resources :locations, except: [:show] do
      resources :menus, only: [:index, :new]
    end
    resources :menus, except: [:new, :show] do
      resources :sections, only: [:new, :create]
    end
    resources :categories do
      resources :category_sections, only: [:new]
    end
    resources :category_sections, except: [:index, :show, :new] do
      resources :category_options, only: [:new]
    end
    resources :category_options, except: [:index, :show, :new]
    resources :items, except: [:show]
    resources :sections, only: [:edit, :update, :destroy] do
      resources :section_items, only: [:new, :create]
    end
    resources :section_items, only: [:edit, :update, :destroy]
    resources :employees
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:show]
    root to: "orders#index"
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post 'firebase_registrations' => "firebase_registrations#update"
      resources :orders, only: [:update]
      resources :locations do
        resources :orders, only: [:index]
      end
      resources :restaurants, only: [:index]
    end
  end

  resources :restaurants, only: [:show]

  get '/restaurants' => "restaurants#show", as: :customer_root
  resources :orders, only: [:new, :create]

  resources :menus, only: [:show]
  resources :locations, only: []  do
    resources :menus, only: [:index]
  end

  resources :items, only: [] do
    resources :bag_items, only: [:new]
  end
  resources :bag_items, only: [:create, :destroy]
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :menu
  has_many :section_items, -> { order(:position) }, dependent: :destroy
  has_many :items, through: :section_items

  acts_as_list scope: :menu

  validates :name, presence: true, length: { maximum: 100 }
  validates :description, length: { maximum: 499 }
  validates :position, numericality: { minimum: 1, only_integer: true }

  scope :sorted, -> { order("sections.position") }
end

app/controllers/admin/sections_controller.rb
# Controller that handles section actions logic. It's a subclass of admin controller as it's an admin controller.
class Admin::SectionsController < Admin::AdminController
  before_action :set_section, only: [:edit, :update, :destroy]

  layout 'admin'

  # GET /admin/menus/1/sections/new
  def new
    @section = Section.new(menu_id: params[:menu_id])
    @sections_count = Section.where(menu_id: params[:menu_id]).count + 1
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /admin/sections
  # POST /admin/sections.json
  def create
    @section = Section.new(section_params)
    @section.menu_id = params[:menu_id]
    respond_to do |format|
      if @section.save
        format.html { redirect_to menu_url(@section.menu_id), notice: 'Section was successfully created.' }
        format.js {
          @sections = Section.where(menu_id: @section.menu_id).order(:position)
          flash[:notice] = "Section was successfully updated."
          render :index
        }
      else
        format.html { render :new }
        format.js {
          @sections_count = Section.where(menu_id: @menu.id).count + 1
          render :new
        }
      end
    end
  end

  # GET /admin/sections/1/edit
  def edit
    @sections_count = Section.where(menu_id: @section.menu_id).count
    respond_to do |format|
      format.html
      format.js
    end
  end

  # PATCH/PUT /admin/sections/1
  # PATCH/PUT /admin/sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to menu_url(@section.menu_id), notice: 'Section was successfully updated.' }
        format.js {
          @sections = Section.where(menu_id: @section.menu_id).order(:position)
          flash[:notice] = "Section was successfully updated."
          render :index
        }
      else
        format.html { render :edit }
        format.js { @sections_count = Section.where(menu_id: @section.menu_id).count
          render :edit
        }
      end
    end
  end

  # DELETE /admin/sections/1
  # DELETE /admin/sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to menu_url(@section.menu_id), notice: 'Section was successfully destroyed.' }
      format.js {
        @sections = Section.where(menu_id: @section.menu_id).order(:position)
        flash[:notice] = "Section was successfully deleted."
        render :index
      }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:menu_id, :name, :description, :position)
    end
end

app/views/admin/sections/_form.html.erb
<%= form_for(@section, url: url, remote: remote) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %> (Optional)<br>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :position %>
    <%= f.select :position, 1..@sections_count, {}, { class: "form-control" } %>
  </div>

  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
  </div>
  
<% end %>

app/views/admin/sections/_index.html.erb
<% count = 0 %>
<% sections.each do |section| %>
  <div class="panel panel-default">
      <div class="panel-heading">
          <h4 class="panel-title">
              <a data-toggle="collapse" href="#section<%= section.id %>">
                <%= section.name %>
                <%= link_to edit_admin_section_path(section.id), remote: true do %>
                  <i class="fa fa-fw fa-pencil-square-o" data-toggle="tooltip" data-placement="top" title="Edit this Section in the Menu"></i>
                <% end %>
                <%= link_to admin_section_path(section.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
                  <i class="fa fa-fw fa-trash-o" data-toggle="tooltip" data-placement="top" title="Remove this Section from the Menu"></i>
                <% end %>
                <%= link_to new_admin_section_section_item_path(section.id), remote: true do %>
                  <i class="fa fa-fw fa-plus-square" data-toggle="tooltip" data-placement="top" title="Add Item in this Section of the Menu"></i>
                <% end %>
              </a>
          </h4>
      </div>
      <!-- .panel-heading -->
      <div id="section<%= section.id %>" class="panel-collapse collapse <%= count == 0 ? 'in' : '' %>">
        <div class="panel-body">
          <p class="lead"><%= section.description %></p>
          <div id="section_items<%= section.id %>" class="row">
            <%= render 'admin/section_items/index', section_items: section.section_items %>
          </div>
          <!-- /.col-sm-4 -->
        </div>
      </div>
      <!-- .panel-collapse -->

  </div>
  <!-- .panel-default -->
  <% count += 1 %>
<% end %>

app/views/admin/sections/edit.js.erb
$('#modalFormBody').html("<%= escape_javascript(render 'form', url: admin_section_path(@section.id), remote: true) %>");
$('#modalForm').modal('show');
$('#modalFormTitle').html("Edit this Section of the Menu");

app/views/admin/sections/index.js.erb
$('#sections<%= @section.menu_id %>').html("<%= escape_javascript(render 'index', sections: @sections) %>");
$('#modalForm').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
initTooltip();

app/views/admin/sections/new.js.erb
$('#modalFormBody').html("<%= escape_javascript(render 'form', url: admin_menu_sections_path(@section.menu_id), remote: true) %>");
$('#modalForm').modal('show');
$('#modalFormTitle').html("Create a New Section to the Menu");