config/routes.rb
Rails.application.routes.draw do

  post 'employee_token' => 'employee_token#create'
  devise_for :customers
  devise_for :employees

  namespace :admin do
    resources :restaurants, except: [:index, :create, :destroy]
    resources :locations, except: [:show] do
      resources :menus, only: [:index, :new]
    end
    resources :menus, except: [:new, :show] do
      resources :sections, only: [:new, :create]
    end
    resources :categories do
      resources :category_sections, only: [:new]
    end
    resources :category_sections, except: [:index, :show, :new] do
      resources :category_options, only: [:new]
    end
    resources :category_options, except: [:index, :show, :new]
    resources :items, except: [:show]
    resources :sections, only: [:edit, :update, :destroy] do
      resources :section_items, only: [:new, :create]
    end
    resources :section_items, only: [:edit, :update, :destroy]
    resources :employees
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:show]
    root to: "orders#index"
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post 'firebase_registrations' => "firebase_registrations#update"
      resources :orders, only: [:update]
      resources :locations do
        resources :orders, only: [:index]
      end
      resources :restaurants, only: [:index]
    end
  end

  resources :restaurants, only: [:show]

  get '/restaurants' => "restaurants#show", as: :customer_root
  resources :orders, only: [:new, :create]

  resources :menus, only: [:show]
  resources :locations, only: []  do
    resources :menus, only: [:index]
  end

  resources :items, only: [] do
    resources :bag_items, only: [:new]
  end
  resources :bag_items, only: [:create, :destroy]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_many :category_sections, -> { order(:position) }, dependent: :destroy
  has_many :category_options, through: :category_sections

  validates :category, presence: true, length: { maximum: 50 }

  scope :sorted, -> { order(:position) }
end

app/controllers/admin/categories_controller.rb
# Controller that handles category actions logic. It's a subclass of admin controller as it's an admin controller.
class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  # GET /admin/categories
  # GET /admin/categories.js
  def index
    @categories = Category.all
    respond_to do |format|
      format.html {
        render '_index'
      }
      format.js
    end
  end

  # GET /admin/categories/1
  def show
  end

  # GET /admin/categories/new
  # GET /admin/categories/new.js
  def new
    @category = Category.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /admin/categories
  # POST /admin/categories.js
  def create
    @category = Category.new(category_params)
    @category.restaurant_id = current_employee.restaurant_id
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.js {
          @categories = Category.all
          flash[:notice] = "Category was successfully created."
          render :index
        }
      else
        format.html { render :new }
        format.js { render :new }
      end
    end
  end

  # GET /items/1/edit
  # GET /items/1/edit.js
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # PATCH/PUT /admin/categories/1
  # PATCH/PUT /admin/categories/1.js
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.js {
          @categories = Category.all
          flash[:notice] = "Category was successfully updated."
          render :index
        }
      else
        format.html { render :edit }
        format.js { render :edit }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.js
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully deleted.' }
      format.js {
        @categories = Category.all
        flash[:notice] = "Category was successfully deleted."
        render :index
      }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/views/admin/categories/_form.html.erb
<%= form_for(@category, url: url, remote: remote) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category, class: "form-control" %>
  </div>

  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/categories/_index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
    <h1>
      Categories
      <!-- We use remote to use Ajax  -->
      <%= link_to new_admin_category_path, remote: true do %>
        <i class="fa fa-fw fa-plus-square" data-toggle="tooltip" data-placement="top" title="Create Category"></i>
      <% end %>
    </h1>
</div>

<!-- We include the modal form which will be loaded through boostrap javascript
     when clicking on the add or update icon  -->
<%= render 'application/modal_form' %>

<div class="row">
  <div class="col-md-6">
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>Category</th>
                    <th>Operations</th>
                </tr>
            </thead>
            <tbody>
              <% @categories.each do |category| %>
                <tr>
                    <td>
                      <%= link_to admin_category_path(category.id)  do %>
                        <span title="See details"><%= category.category %></span>
                      <% end %>
                    </td>
                    <td class="text-center">
                      <%= link_to edit_admin_category_path(category.id), remote: true do %>
                        <i class="fa fa-fw fa-pencil-square-o" data-toggle="tooltip" data-placement="top" title="Edit Category"></i>
                      <% end %>
                      <%= link_to admin_category_path(category.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
                        <i class="fa fa-fw fa-trash-o" data-toggle="tooltip" data-placement="top" title="Delete Category"></i>
                      <% end %>
                    </td>
                </tr>
              <% end %>
            </tbody>
        </table>
    </div>
  </div>
</div>
<!-- /.row -->

app/views/admin/categories/edit.js.erb
$('#modalFormBody').html("<%= escape_javascript(render 'form', url: admin_category_path(@category.id), remote: true) %>");
$('#modalForm').modal('show');
$('#modalFormTitle').html("Edit category");

app/views/admin/categories/index.js.erb
$('.main').html("<%= escape_javascript(render 'index') %>");
$('#modalForm').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
initTooltip();

app/views/admin/categories/new.js.erb
$('#modalFormBody').html("<%= escape_javascript(render 'form', url: admin_categories_path, remote: true) %>");
$('#modalForm').modal('show');
$('#modalFormTitle').html("Add category");

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-4">
      <h2>
        <%= @category.category %>
        <!-- We use remote to use Ajax  -->
        <%= link_to new_admin_category_category_section_path(@category.id), remote: true do %>
          <i class="fa fa-fw fa-plus-square" data-toggle="tooltip" data-placement="top" title="Create Category Option"></i>
        <% end %>
      </h2>
  </div>
  <!-- /.col-md-4 -->
</div>
<!-- /.row -->

<!-- We include the modal form which will be loaded through boostrap javascript
     when clicking on the add or update icon  -->
<%= render 'application/modal_form' %>

<div class="row">
  <div id="categorySections" class="col-md-8">
    <%= render 'admin/category_sections/index', category_sections: @category.category_sections %>
  </div>
  <!-- /.col-md-8 -->
</div>
<!-- /.row -->